export const data = {
    products: [
        {
            id: '1',
            name: 'Foundation',
            price: 50,
            description: 'This is our best selling foundation!', 
            type: 'Makeup',
            like: 0,    
            imgSrc: '/img/foundation.jpg', 
        },
        {
            id: '2',
            name: 'Blush',
            price: 30,
            description: 'This is our best selling blush!', 
            type:'Makeup',
            like: 0,      
            imgSrc: '/img/blush.jpg',
        },
        {
            id: '3',
            name: 'Facial Cleanser',
            price: 70,
            description: 'This is our best selling facial cleanser!', 
            type:'Skincare',
            like: 0,    
            imgSrc:'/img/face-cleanser.jpg',
        },
        {
            id: '4',
            name: 'Deep Sunrise Eyeshadow',
            price: 45,
            description: 'This is our best selling eyeshadow', 
            type:'Makeup',
            like: 0,    
            imgSrc:'/img/eyeshadow.jpg',
        },
        {
            id: '5',
            name: 'Hydrating Toner',
            price: 30,
            description: 'This is our best selling toner', 
            type:'Skincare',
            like: 2,    
            imgSrc:'/img/toner.jpg',
        },
        {
            id: '6',
            name: 'Water Cream Moisturizer',
            price: 80,
            description: 'This is our best selling moisturizer', 
            type:'skincare',
            like: 0,    
            imgSrc:'/img/moisturizer.jpg',
        }, 
        {
            id:'7',
            name: 'Lip Glowy Balm',
            price: 30,
            description: 'This is our best selling lip balm', 
            type:'skincare',
            like: 3,    
            imgSrc:'/img/lipbalm.jpg',
        }
    ],
    cart: {
        products:[{
            id: '1',
            name: 'Foundation',
            price: 50,
            description: 'This is our best foundation', 
            type: 'Makeup',   
            like: 0, 
            cartQty: 1, 
            cartTotal:50,   
            imgSrc: '/img/foundation.jpg', 
        },
        {
            id: '2',
            name: 'Blush',
            price: 30,
            description: 'This is our best blush', 
            type:'Makeup',  
            like: 0,
            cartQty: 1, 
            cartTotal:30, 
            imgSrc: '/img/blush.jpg',
        }],
        totalQty:2,
        totalAmt:80,
    }
}